### PR TITLE
Upgrade Wildfly Swarm to Thorntail

### PR DESCRIPTION
**Pull request by juangon**
Hi!

I upgraded these tests so they can pass with new Thorntail versions.

Want to highlight 2 changes made and their reasons:

* Added better ExecutionException check. As stated in https://github.com/eclipse/microprofile-fault-tolerance/blob/master/spec/src/main/asciidoc/asynchronous.asciidoc#exception-handling, ExecutionException can wrap the exceptions from Bulkhead, Timeout, etc.
* In circuitbreaker tests, I added 1 change:
  *  As there could be problems when using concurrent request (it may happen that circuit isn't open when throwing the exact number of request to get expected number of requests) I changed requests to be sequential by using newSingleThread executor.

### CODE REVIEW

**Comment by Ladicek** [comment]
Looking good to me.

I'm sure we talked about this before, but can't remember, so I'll ask again: wouldn't enabling `thorntail.microprofile.fault-tolerance.synchronous-circuit-breaker` make sure that the circuit breaker will open after that exact number of requests?

**Comment by juangon** [comment]
Yes, I tested that and didn't work: https://github.com/javaee-samples/microprofile1.2-samples/pull/5#issuecomment-444512058

**Review by arjantijms — APPROVED** [review]

**Comment by juangon** [comment]
@arjantijms I wonder if there is any plan to add microprofile 2.x samples repository, using the same approach made in microprofile-1.2-samples and microprofile-1.4-samples.

Thanks!

**Comment by arjantijms** [comment]
@juangon absolutely!

Just need some time ;)

**Comment by juangon** [comment]
Thanks @arjantijms ! I think you are doing a great job with these repositories BTW.

**Pull request merged**
